#ifndef LIBRETRO_CORE_OPTIONS_INTL_H__
#define LIBRETRO_CORE_OPTIONS_INTL_H__

#if defined(_MSC_VER) && (_MSC_VER >= 1500 && _MSC_VER < 1900)
#pragma execution_character_set("utf-8")
#pragma warning(disable:4566)
#endif

#include <libretro.h>

/*
 ********************************
 * VERSION: 2.0
 ********************************
 */

#ifdef __cplusplus
extern "C" {
#endif

/* RETRO_LANGUAGE_JAPANESE */

/* RETRO_LANGUAGE_FRENCH */

/* RETRO_LANGUAGE_SPANISH */

/* RETRO_LANGUAGE_GERMAN */

/* RETRO_LANGUAGE_ITALIAN */

/* RETRO_LANGUAGE_DUTCH */

/* RETRO_LANGUAGE_PORTUGUESE_BRAZIL */

/* RETRO_LANGUAGE_PORTUGUESE_PORTUGAL */

/* RETRO_LANGUAGE_RUSSIAN */

/* RETRO_LANGUAGE_KOREAN */

/* RETRO_LANGUAGE_CHINESE_TRADITIONAL */

/* RETRO_LANGUAGE_CHINESE_SIMPLIFIED */

struct retro_core_option_v2_category option_cats_chs[] = {
   {
      "cheat",
      "金手指",
      "游戏内置的金手指，本功能为mod特有，若遇到金手指不对或者需要增加金手指，请联系qq2670878301"
   },
   {
      "system",
      "系统",
      "配置基础硬件参数：区域、BIOS 选择、记忆卡等。"
   },
   {
      "video",
      "视频",
      "配置基础显示参数。"
   },
#ifdef GPU_NEON
   {
      "gpu_neon",
      "GPU 插件",
      "配置 NEON GPU 插件底层设置。"
   },
#endif
#ifdef GPU_PEOPS
   {
      "gpu_peops",
      "GPU 插件 (高级)",
      "配置 P.E.Op.S. GPU 插件底层设置。"
   },
#endif
#ifdef GPU_UNAI
   {
      "gpu_unai",
      "GPU 插件 (高级)",
      "配置 UNAI GPU 插件底层设置。"
   },
#endif
   {
      "audio",
      "音频",
      "配置声音模拟：混响、插值、CD 音频解码。"
   },
   {
      "input",
      "输入",
      "配置输入设备：模拟响应、触觉反馈、分插、光枪等。"
   },
   {
      "compat_hack",
      "兼容性修复",
      "配置特定游戏正确运行所需的设置/修正。"
   },
   {
      "speed_hack",
      "速度优化 (高级)",
      "配置可能以降低精度/稳定性为代价提高性能的优化。"
   },
   { NULL, NULL, NULL },
};

struct retro_core_option_v2_definition option_defs_chs[] = {
   {
      "pcsx_rearmed_region",
      "区域",
      NULL,
      "指定主机区域。NTSC 60Hz，PAL 50Hz。",
      NULL,
      NULL,
      {
         { "auto", "自动" },
         { "NTSC", "NTSC" },
         { "PAL", "PAL" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_bios",
      "BIOS 选择",
      NULL,
      "指定使用的 BIOS。建议使用官方 BIOS。",
      NULL,
      NULL,
      {
         { "auto", "自动" },
         { "HLE", "HLE" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_show_bios_bootlogo",
      "显示 BIOS 启动标志",
      NULL,
      "使用自定义 BIOS 时显示文件名和启动标志。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { "enabled_no_pcsx", "启用(无PCSXtm)" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_memcard1",
      "记忆卡 1 类型 (重启)",
      NULL,
      "模拟插槽 1 记忆卡的方式。",
      NULL,
      NULL,
      {
         { "libretro", "Libretro(默认)" },
         { "serial", "游戏代码" },
         { "shared", "共享" },
         { "none", "无" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_memcard2",
      "记忆卡 2 类型",
      NULL,
      "模拟插槽 2 记忆卡的方式。",
      NULL,
      NULL,
      {
         { "serial", "游戏代码" },
         { "shared", "共享" },
         { "none", "无" },
         { NULL, NULL },
      },
      NULL,
   },
#if defined(HAVE_CDROM) || defined(USE_ASYNC_CDROM)
#define V(x) { #x, NULL }
   {
      "pcsx_rearmed_cd_readahead",
      "CD 预读",
      NULL,
      "启用 CD 预读以改善加载速度。",
      NULL,
      NULL,
      {
         { "12", NULL },
         { NULL, NULL },
      },
      NULL,
   },
#undef V
#endif
#ifndef DRC_DISABLE
   {
      "pcsx_rearmed_drc",
      "动态重编译器",
      NULL,
      "启用动态重编译器以大幅提高性能。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
#if !defined(LIGHTREC) && defined(NDRC_THREAD)
   {
      "pcsx_rearmed_drc_thread",
      "动态重编译线程",
      NULL,
      "在独立线程中运行动态重编译器。",
      NULL,
      NULL,
      {
         { "auto", "自动" },
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
#endif
#endif // DRC_DISABLE
   {
      "pcsx_rearmed_psxclock",
      "PSX CPU 时钟速度 (%)",
      NULL,
      "调整模拟 CPU 频率。",
      NULL,
      NULL,
      {
         { "auto", "自动" },
         { "30", NULL },
         { "31", NULL },
         { "32", NULL },
         { "33", NULL },
         { "34", NULL },
         { "35", NULL },
         { "36", NULL },
         { "37", NULL },
         { "38", NULL },
         { "39", NULL },
         { "40", NULL },
         { "41", NULL },
         { "42", NULL },
         { "43", NULL },
         { "44", NULL },
         { "45", NULL },
         { "46", NULL },
         { "47", NULL },
         { "48", NULL },
         { "49", NULL },
         { "50", NULL },
         { "51", NULL },
         { "52", NULL },
         { "53", NULL },
         { "54", NULL },
         { "55", NULL },
         { "56", NULL },
         { "57", NULL },
         { "58", NULL },
         { "59", NULL },
         { "60", NULL },
         { "61", NULL },
         { "62", NULL },
         { "63", NULL },
         { "64", NULL },
         { "65", NULL },
         { "66", NULL },
         { "67", NULL },
         { "68", NULL },
         { "69", NULL },
         { "70", NULL },
         { "71", NULL },
         { "72", NULL },
         { "73", NULL },
         { "74", NULL },
         { "75", NULL },
         { "76", NULL },
         { "77", NULL },
         { "78", NULL },
         { "79", NULL },
         { "80", NULL },
         { "81", NULL },
         { "82", NULL },
         { "83", NULL },
         { "84", NULL },
         { "85", NULL },
         { "86", NULL },
         { "87", NULL },
         { "88", NULL },
         { "89", NULL },
         { "90", NULL },
         { "91", NULL },
         { "92", NULL },
         { "93", NULL },
         { "94", NULL },
         { "95", NULL },
         { "96", NULL },
         { "97", NULL },
         { "98", NULL },
         { "99", NULL },
         { "100", NULL },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_dithering",
      "抖动模式",
      NULL,
      "选择抖动模式。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { "force", "强制" },
         { NULL, NULL },
      },
      NULL,
   },
#ifdef USE_ASYNC_GPU
   {
      "pcsx_rearmed_gpu_thread_rendering",
      "线程渲染",
      NULL,
      "在独立线程中运行 GPU 渲染。",
      NULL,
      NULL,
      {
         { "auto", "自动" },
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
#endif
   {
      "pcsx_rearmed_frameskip_type",
      "跳帧模式",
      NULL,
      "跳帧以避免音频缓冲欠载（爆音）。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "auto", "自动" },
         { "auto_threshold", "自动(阈值)" },
         { "fixed_interval", "固定间隔" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_frameskip_threshold",
      "跳帧阈值 (%)",
      NULL,
      "当跳帧模式设为自动阈值时指定音频缓冲占用阈值。",
      NULL,
      NULL,
      {
         { "15", NULL },
         { "18", NULL },
         { "21", NULL },
         { "24", NULL },
         { "27", NULL },
         { "30", NULL },
         { "33", NULL },
         { "36", NULL },
         { "39", NULL },
         { "42", NULL },
         { "45", NULL },
         { "48", NULL },
         { "51", NULL },
         { "54", NULL },
         { "57", NULL },
         { "60", NULL },
         { "65", NULL },
         { "70", NULL },
         { "75", NULL },
         { "80", NULL },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_frameskip_interval",
      "跳帧间隔",
      NULL,
      "当跳帧模式设为固定间隔时的跳帧间隔。",
      NULL,
      NULL,
      {
         { "1", NULL },
         { "2", NULL },
         { "3", NULL },
         { "4", NULL },
         { "5", NULL },
         { "6", NULL },
         { "7", NULL },
         { "8", NULL },
         { "9", NULL },
         { "10", NULL },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_display_fps_v2",
      "显示内部帧率",
      NULL,
      "在屏幕上显示内部模拟帧率。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { "extra", "扩展" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_fractional_framerate",
      "使用分数帧率",
      NULL,
      "启用分数帧率支持。",
      NULL,
      NULL,
      {
         { "auto", "自动" },
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_alt_flip",
      "帧缓冲读取",
      NULL,
      "选择帧缓冲读取方式。",
      NULL,
      NULL,
      {
         { "auto", "自动" },
         { "early", "提前" },
         { "late", "延迟" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_rgb32_output",
      "RGB32 输出",
      NULL,
      "使用 32 位色深输出。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_scale_hires",
      "高分辨率降采样",
      NULL,
      "将高分辨率模式降采样。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_gpu_slow_llists",
      "(GPU) 慢速链表处理",
      NULL,
      "使用慢速链表处理模式。",
      NULL,
      NULL,
      {
         { "auto", "自动" },
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_show_overscan",
      "(GPU) 水平过扫描",
      NULL,
      "显示水平过扫描区域。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "auto", "自动" },
         { "hack", "修正" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_screen_centering",
      "(GPU) 屏幕居中",
      NULL,
      "控制屏幕居中模式。",
      NULL,
      NULL,
      {
         { "auto", "自动" },
         { "game", "游戏控制" },
         { "borderless", "无边框" },
         { "manual", "手动" },
         { NULL, NULL },
      },
      NULL,
   },
#define V(x) { #x, NULL }
   {
      "pcsx_rearmed_screen_centering_x",
      "(GPU) 手动位置 X",
      NULL,
      "手动调整屏幕水平位置。",
      NULL,
      NULL,
      {
         { "0", "关闭" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_screen_centering_y",
      "(GPU) 手动位置 Y",
      NULL,
      "手动调整屏幕垂直位置。",
      NULL,
      NULL,
      {
         { "0", "关闭" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_screen_centering_h_adj",
      "(GPU) 手动高度调整",
      NULL,
      "手动调整屏幕显示高度。",
      NULL,
      NULL,
      {
         { "0", "关闭" },
         { NULL, NULL },
      },
      NULL,
   },
#undef V
#ifdef GPU_NEON
   {
      "pcsx_rearmed_neon_interlace_enable_v2",
      "(GPU) 显示隔行视频",
      NULL,
      "启用隔行扫描视频显示。",
      NULL,
      NULL,
      {
         { "auto", "自动" },
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_neon_enhancement_enable",
      "(GPU) 增强分辨率",
      NULL,
      "启用增强分辨率渲染。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_neon_enhancement_no_main",
      "(GPU) 增强分辨率加速",
      NULL,
      "加速增强分辨率渲染。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_neon_enhancement_tex_adj_v2",
      "(GPU) 增强分辨率纹理调整",
      NULL,
      "调整增强分辨率下的纹理坐标。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
#endif /* GPU_NEON */
#ifdef GPU_PEOPS
   {
      "pcsx_rearmed_show_gpu_peops_settings",
      "显示高级 P.E.Op.S. GPU 设置",
      NULL,
      "显示 P.E.Op.S. GPU 的高级设置。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_gpu_peops_odd_even_bit",
      "(GPU) 奇偶位修正",
      NULL,
      "启用奇偶位修正。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_gpu_peops_expand_screen_width",
      "(GPU) 扩展屏幕宽度",
      NULL,
      "扩展屏幕宽度。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_gpu_peops_ignore_brightness",
      "(GPU) 忽略亮度颜色",
      NULL,
      "忽略亮度颜色信息。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_gpu_peops_disable_coord_check",
      "(GPU) 禁用坐标检查",
      NULL,
      "禁用坐标检查。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_gpu_peops_lazy_screen_update",
      "(GPU) 延迟屏幕更新",
      NULL,
      "延迟屏幕更新以提高性能。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_gpu_peops_repeated_triangles",
      "(GPU) 重复平面纹理三角形",
      NULL,
      "重复绘制平面纹理三角形。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_gpu_peops_quads_with_triangles",
      "(GPU) 用三角形绘制纹理四边形",
      NULL,
      "使用三角形代替四边形绘制纹理。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_gpu_peops_fake_busy_state",
      "(GPU) 伪造 GPU 忙碌状态",
      NULL,
      "伪造 GPU 忙碌状态。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
#endif /* GPU_PEOPS */
#ifdef GPU_UNAI
   {
      "pcsx_rearmed_show_gpu_unai_settings",
      "显示高级 UNAI GPU 设置",
      NULL,
      "显示 UNAI GPU 的高级设置。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
#ifndef GPU_UNAI_NO_OLD
   {
      "pcsx_rearmed_gpu_unai_old_renderer",
      "(GPU) 旧版渲染器",
      NULL,
      "使用旧版渲染器。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
#endif
   {
      "pcsx_rearmed_gpu_unai_blending",
      "(GPU) 纹理混合",
      NULL,
      "启用纹理混合效果。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_gpu_unai_skipline",
      "(GPU) 隔行跳过",
      NULL,
      "跳过每隔一行渲染。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_gpu_unai_lighting",
      "(GPU) 光照效果",
      NULL,
      "启用光照效果。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_gpu_unai_fast_lighting",
      "(GPU) 快速光照",
      NULL,
      "使用快速光照算法。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
#endif /* GPU_UNAI */
   {
      "pcsx_rearmed_spu_reverb",
      "音频混响效果",
      NULL,
      "启用音频混响效果。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_spu_interpolation",
      "音频插值",
      NULL,
      "配置音频插值模式。",
      NULL,
      NULL,
      {
         { "simple", "简单" },
         { "gaussian", "高斯" },
         { "cubic", "三次" },
         { "off", "关闭" },
         { "disabled", "禁用" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_nocdaudio",
      "CD 音频",
      NULL,
      "启用 CD 音频曲目。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_noxadecoding",
      "XA 解码",
      NULL,
      "启用 XA 音频解码。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
#ifdef USE_ASYNC_SPU
   {
      "pcsx_rearmed_spu_thread",
      "线程化 SPU",
      NULL,
      "在独立线程中运行 SPU。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
#endif
   {
      "pcsx_rearmed_show_input_settings",
      "显示输入设置",
      NULL,
      "显示输入设备的详细设置。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_analog_axis_modifier",
      "摇杆轴范围",
      NULL,
      "调整模拟摇杆的轴响应范围。",
      NULL,
      NULL,
      {
         { "circle", "圆形" },
         { "square", "方形" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_vibration",
      "震动效果",
      NULL,
      "启用手柄震动反馈。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_analog_combo",
      "DualShock 模拟模式切换组合键",
      NULL,
      "设置 DualShock 模拟模式切换组合键。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "l1+r1+select", "L1+R1+Select" },
         { "l1+r1+start", "L1+R1+Start" },
         { "l1+r1+l3", "L1+R1+L3" },
         { "l1+r1+r3", "L1+R1+R3" },
         { "l3+r3", "L3+R3" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_multitap",
      "分插器模式",
      NULL,
      "启用分插器设备。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "port 1", "端口1" },
         { "port 2", "端口2" },
         { "ports 1 and 2", "端口1和2" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_negcon_deadzone",
      "NegCon 扭转死区",
      NULL,
      "设置 NegCon 手柄扭转死区。",
      NULL,
      NULL,
      {
         { "0", "关闭" },
         { "3", NULL },
         { "5", NULL },
         { "7", NULL },
         { "10", NULL },
         { "13", NULL },
         { "15", NULL },
         { "17", NULL },
         { "20", NULL },
         { "23", NULL },
         { "25", NULL },
         { "27", NULL },
         { "30", NULL },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_negcon_response",
      "NegCon 扭转响应",
      NULL,
      "调整 NegCon 手柄扭转响应。",
      NULL,
      NULL,
      {
         { "linear", "线性" },
         { "quadratic", "二次" },
         { "cubic", "三次" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_input_sensitivity",
      "鼠标灵敏度",
      NULL,
      "调整鼠标输入灵敏度。",
      NULL,
      NULL,
      {
         { "0.05", NULL },
         { "0.10", NULL },
         { "0.15", NULL },
         { "0.20", NULL },
         { "0.25", NULL },
         { "0.30", NULL },
         { "0.35", NULL },
         { "0.40", NULL },
         { "0.45", NULL },
         { "0.50", NULL },
         { "0.55", NULL },
         { "0.60", NULL },
         { "0.65", NULL },
         { "0.70", NULL },
         { "0.75", NULL },
         { "0.80", NULL },
         { "0.85", NULL },
         { "0.90", NULL },
         { "0.95", NULL },
         { "1.00", NULL },
         { "1.05", NULL },
         { "1.10", NULL },
         { "1.15", NULL },
         { "1.20", NULL },
         { "1.25", NULL },
         { "1.30", NULL },
         { "1.35", NULL },
         { "1.40", NULL },
         { "1.45", NULL },
         { "1.50", NULL },
         { "1.55", NULL },
         { "1.60", NULL },
         { "1.65", NULL },
         { "1.70", NULL },
         { "1.75", NULL },
         { "1.80", NULL },
         { "1.85", NULL },
         { "1.90", NULL },
         { "1.95", NULL },
         { "2.00", NULL },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_crosshair1",
      "玩家 1 光枪准星",
      NULL,
      "控制玩家 1 光枪准星显示。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "blue", "蓝色" },
         { "green", "绿色" },
         { "red", "红色" },
         { "white", "白色" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_crosshair2",
      "玩家 2 光枪准星",
      NULL,
      "控制玩家 2 光枪准星显示。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "blue", "蓝色" },
         { "green", "绿色" },
         { "red", "红色" },
         { "white", "白色" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_konamigunadjustx",
      "柯乐美光枪 X 轴偏移",
      NULL,
      "调整柯乐美光枪 X 轴偏移。",
      NULL,
      NULL,
      {
         { "-40", NULL },
         { "-39", NULL },
         { "-38", NULL },
         { "-37", NULL },
         { "-36", NULL },
         { "-35", NULL },
         { "-34", NULL },
         { "-33", NULL },
         { "-32", NULL },
         { "-31", NULL },
         { "-30", NULL },
         { "-29", NULL },
         { "-28", NULL },
         { "-27", NULL },
         { "-26", NULL },
         { "-25", NULL },
         { "-24", NULL },
         { "-23", NULL },
         { "-22", NULL },
         { "-21", NULL },
         { "-20", NULL },
         { "-19", NULL },
         { "-18", NULL },
         { "-17", NULL },
         { "-16", NULL },
         { "-15", NULL },
         { "-14", NULL },
         { "-13", NULL },
         { "-12", NULL },
         { "-11", NULL },
         { "-10", NULL },
         { "-9", NULL },
         { "-8", NULL },
         { "-7", NULL },
         { "-6", NULL },
         { "-5", NULL },
         { "-4", NULL },
         { "-3", NULL },
         { "-2", NULL },
         { "-1", NULL },
         { "0", "关闭" },
         { "1", NULL },
         { "2", NULL },
         { "3", NULL },
         { "4", NULL },
         { "5", NULL },
         { "6", NULL },
         { "7", NULL },
         { "8", NULL },
         { "9", NULL },
         { "10", NULL },
         { "11", NULL },
         { "12", NULL },
         { "13", NULL },
         { "14", NULL },
         { "15", NULL },
         { "16", NULL },
         { "17", NULL },
         { "18", NULL },
         { "19", NULL },
         { "20", NULL },
         { "21", NULL },
         { "22", NULL },
         { "23", NULL },
         { "24", NULL },
         { "25", NULL },
         { "26", NULL },
         { "27", NULL },
         { "28", NULL },
         { "29", NULL },
         { "30", NULL },
         { "31", NULL },
         { "32", NULL },
         { "33", NULL },
         { "34", NULL },
         { "35", NULL },
         { "36", NULL },
         { "37", NULL },
         { "38", NULL },
         { "39", NULL },
         { "40", NULL },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_konamigunadjusty",
      "柯乐美光枪 Y 轴偏移",
      NULL,
      "调整柯乐美光枪 Y 轴偏移。",
      NULL,
      NULL,
      {
         { "-40", NULL },
         { "-39", NULL },
         { "-38", NULL },
         { "-37", NULL },
         { "-36", NULL },
         { "-35", NULL },
         { "-34", NULL },
         { "-33", NULL },
         { "-32", NULL },
         { "-31", NULL },
         { "-30", NULL },
         { "-29", NULL },
         { "-28", NULL },
         { "-27", NULL },
         { "-26", NULL },
         { "-25", NULL },
         { "-24", NULL },
         { "-23", NULL },
         { "-22", NULL },
         { "-21", NULL },
         { "-20", NULL },
         { "-19", NULL },
         { "-18", NULL },
         { "-17", NULL },
         { "-16", NULL },
         { "-15", NULL },
         { "-14", NULL },
         { "-13", NULL },
         { "-12", NULL },
         { "-11", NULL },
         { "-10", NULL },
         { "-9", NULL },
         { "-8", NULL },
         { "-7", NULL },
         { "-6", NULL },
         { "-5", NULL },
         { "-4", NULL },
         { "-3", NULL },
         { "-2", NULL },
         { "-1", NULL },
         { "0", "关闭" },
         { "1", NULL },
         { "2", NULL },
         { "3", NULL },
         { "4", NULL },
         { "5", NULL },
         { "6", NULL },
         { "7", NULL },
         { "8", NULL },
         { "9", NULL },
         { "10", NULL },
         { "11", NULL },
         { "12", NULL },
         { "13", NULL },
         { "14", NULL },
         { "15", NULL },
         { "16", NULL },
         { "17", NULL },
         { "18", NULL },
         { "19", NULL },
         { "20", NULL },
         { "21", NULL },
         { "22", NULL },
         { "23", NULL },
         { "24", NULL },
         { "25", NULL },
         { "26", NULL },
         { "27", NULL },
         { "28", NULL },
         { "29", NULL },
         { "30", NULL },
         { "31", NULL },
         { "32", NULL },
         { "33", NULL },
         { "34", NULL },
         { "35", NULL },
         { "36", NULL },
         { "37", NULL },
         { "38", NULL },
         { "39", NULL },
         { "40", NULL },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_gunconadjustx",
      "Guncon X 轴偏移",
      NULL,
      "调整 Guncon 光枪 X 轴偏移。",
      NULL,
      NULL,
      {
         { "-40", NULL },
         { "-39", NULL },
         { "-38", NULL },
         { "-37", NULL },
         { "-36", NULL },
         { "-35", NULL },
         { "-34", NULL },
         { "-33", NULL },
         { "-32", NULL },
         { "-31", NULL },
         { "-30", NULL },
         { "-29", NULL },
         { "-28", NULL },
         { "-27", NULL },
         { "-26", NULL },
         { "-25", NULL },
         { "-24", NULL },
         { "-23", NULL },
         { "-22", NULL },
         { "-21", NULL },
         { "-20", NULL },
         { "-19", NULL },
         { "-18", NULL },
         { "-17", NULL },
         { "-16", NULL },
         { "-15", NULL },
         { "-14", NULL },
         { "-13", NULL },
         { "-12", NULL },
         { "-11", NULL },
         { "-10", NULL },
         { "-9", NULL },
         { "-8", NULL },
         { "-7", NULL },
         { "-6", NULL },
         { "-5", NULL },
         { "-4", NULL },
         { "-3", NULL },
         { "-2", NULL },
         { "-1", NULL },
         { "0", "关闭" },
         { "1", NULL },
         { "2", NULL },
         { "3", NULL },
         { "4", NULL },
         { "5", NULL },
         { "6", NULL },
         { "7", NULL },
         { "8", NULL },
         { "9", NULL },
         { "10", NULL },
         { "11", NULL },
         { "12", NULL },
         { "13", NULL },
         { "14", NULL },
         { "15", NULL },
         { "16", NULL },
         { "17", NULL },
         { "18", NULL },
         { "19", NULL },
         { "20", NULL },
         { "21", NULL },
         { "22", NULL },
         { "23", NULL },
         { "24", NULL },
         { "25", NULL },
         { "26", NULL },
         { "27", NULL },
         { "28", NULL },
         { "29", NULL },
         { "30", NULL },
         { "31", NULL },
         { "32", NULL },
         { "33", NULL },
         { "34", NULL },
         { "35", NULL },
         { "36", NULL },
         { "37", NULL },
         { "38", NULL },
         { "39", NULL },
         { "40", NULL },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_gunconadjusty",
      "Guncon Y 轴偏移",
      NULL,
      "调整 Guncon 光枪 Y 轴偏移。",
      NULL,
      NULL,
      {
         { "-40", NULL },
         { "-39", NULL },
         { "-38", NULL },
         { "-37", NULL },
         { "-36", NULL },
         { "-35", NULL },
         { "-34", NULL },
         { "-33", NULL },
         { "-32", NULL },
         { "-31", NULL },
         { "-30", NULL },
         { "-29", NULL },
         { "-28", NULL },
         { "-27", NULL },
         { "-26", NULL },
         { "-25", NULL },
         { "-24", NULL },
         { "-23", NULL },
         { "-22", NULL },
         { "-21", NULL },
         { "-20", NULL },
         { "-19", NULL },
         { "-18", NULL },
         { "-17", NULL },
         { "-16", NULL },
         { "-15", NULL },
         { "-14", NULL },
         { "-13", NULL },
         { "-12", NULL },
         { "-11", NULL },
         { "-10", NULL },
         { "-9", NULL },
         { "-8", NULL },
         { "-7", NULL },
         { "-6", NULL },
         { "-5", NULL },
         { "-4", NULL },
         { "-3", NULL },
         { "-2", NULL },
         { "-1", NULL },
         { "0", "关闭" },
         { "1", NULL },
         { "2", NULL },
         { "3", NULL },
         { "4", NULL },
         { "5", NULL },
         { "6", NULL },
         { "7", NULL },
         { "8", NULL },
         { "9", NULL },
         { "10", NULL },
         { "11", NULL },
         { "12", NULL },
         { "13", NULL },
         { "14", NULL },
         { "15", NULL },
         { "16", NULL },
         { "17", NULL },
         { "18", NULL },
         { "19", NULL },
         { "20", NULL },
         { "21", NULL },
         { "22", NULL },
         { "23", NULL },
         { "24", NULL },
         { "25", NULL },
         { "26", NULL },
         { "27", NULL },
         { "28", NULL },
         { "29", NULL },
         { "30", NULL },
         { "31", NULL },
         { "32", NULL },
         { "33", NULL },
         { "34", NULL },
         { "35", NULL },
         { "36", NULL },
         { "37", NULL },
         { "38", NULL },
         { "39", NULL },
         { "40", NULL },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_gunconadjustratiox",
      "Guncon X 轴响应",
      NULL,
      "调整 Guncon 光枪 X 轴响应。",
      NULL,
      NULL,
      {
         { "0.75", NULL },
         { "0.76", NULL },
         { "0.77", NULL },
         { "0.78", NULL },
         { "0.79", NULL },
         { "0.80", NULL },
         { "0.81", NULL },
         { "0.82", NULL },
         { "0.83", NULL },
         { "0.84", NULL },
         { "0.85", NULL },
         { "0.86", NULL },
         { "0.87", NULL },
         { "0.88", NULL },
         { "0.89", NULL },
         { "0.90", NULL },
         { "0.91", NULL },
         { "0.92", NULL },
         { "0.93", NULL },
         { "0.94", NULL },
         { "0.95", NULL },
         { "0.96", NULL },
         { "0.97", NULL },
         { "0.98", NULL },
         { "0.99", NULL },
         { "1.00", NULL },
         { "1.01", NULL },
         { "1.02", NULL },
         { "1.03", NULL },
         { "1.04", NULL },
         { "1.05", NULL },
         { "1.06", NULL },
         { "1.07", NULL },
         { "1.08", NULL },
         { "1.09", NULL },
         { "1.10", NULL },
         { "1.11", NULL },
         { "1.12", NULL },
         { "1.13", NULL },
         { "1.14", NULL },
         { "1.15", NULL },
         { "1.16", NULL },
         { "1.17", NULL },
         { "1.18", NULL },
         { "1.19", NULL },
         { "1.20", NULL },
         { "1.21", NULL },
         { "1.22", NULL },
         { "1.23", NULL },
         { "1.24", NULL },
         { "1.25", NULL },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_gunconadjustratioy",
      "Guncon Y 轴响应",
      NULL,
      "调整 Guncon 光枪 Y 轴响应。",
      NULL,
      NULL,
      {
         { "0.75", NULL },
         { "0.76", NULL },
         { "0.77", NULL },
         { "0.78", NULL },
         { "0.79", NULL },
         { "0.80", NULL },
         { "0.81", NULL },
         { "0.82", NULL },
         { "0.83", NULL },
         { "0.84", NULL },
         { "0.85", NULL },
         { "0.86", NULL },
         { "0.87", NULL },
         { "0.88", NULL },
         { "0.89", NULL },
         { "0.90", NULL },
         { "0.91", NULL },
         { "0.92", NULL },
         { "0.93", NULL },
         { "0.94", NULL },
         { "0.95", NULL },
         { "0.96", NULL },
         { "0.97", NULL },
         { "0.98", NULL },
         { "0.99", NULL },
         { "1.00", NULL },
         { "1.01", NULL },
         { "1.02", NULL },
         { "1.03", NULL },
         { "1.04", NULL },
         { "1.05", NULL },
         { "1.06", NULL },
         { "1.07", NULL },
         { "1.08", NULL },
         { "1.09", NULL },
         { "1.10", NULL },
         { "1.11", NULL },
         { "1.12", NULL },
         { "1.13", NULL },
         { "1.14", NULL },
         { "1.15", NULL },
         { "1.16", NULL },
         { "1.17", NULL },
         { "1.18", NULL },
         { "1.19", NULL },
         { "1.20", NULL },
         { "1.21", NULL },
         { "1.22", NULL },
         { "1.23", NULL },
         { "1.24", NULL },
         { "1.25", NULL },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_icache_emulation",
      "指令缓存模拟",
      NULL,
      "启用 CPU 指令缓存模拟。",
      NULL,
      NULL,
      {
         { "enabled", "启用" },
         { "disabled", "禁用" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_exception_emulation",
      "异常和断点模拟",
      NULL,
      "启用异常和断点模拟。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
#ifdef _3DS
#define V(x) { #x, NULL }
   {
      "pcsx_rearmed_3ds_appcputime",
      "3DS AppCpuTimeLimit",
      NULL,
      "设置 3DS CPU 时间限制。",
      NULL,
      NULL,
      {
         { "35", NULL },
         { NULL, NULL },
      },
      NULL,
   },
#undef V
#endif // _3DS
   {
      "pcsx_rearmed_cd_turbo",
      "CD 加速",
      NULL,
      "加速 CD 读取速度。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
#if !defined(DRC_DISABLE) && !defined(LIGHTREC)
   {
      "pcsx_rearmed_nocompathacks",
      "禁用自动兼容性修正",
      NULL,
      "禁用基于游戏数据库的自动修正。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_nosmccheck",
      "(速度优化) 禁用 SMC 检查",
      NULL,
      "可能导致崩溃或损坏记忆卡。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_gteregsunneeded",
      "(速度优化) 假设 GTE 寄存器不需要",
      NULL,
      "可能导致画面闪烁。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
   {
      "pcsx_rearmed_nogteflags",
      "(速度优化) 禁用 GTE 标志",
      NULL,
      "会导致渲染错误。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
#endif /* !DRC_DISABLE && !LIGHTREC */
   {
      "pcsx_rearmed_nostalls",
      "禁用 CPU/GTE 暂停",
      NULL,
      "会导致部分游戏运行过快。翻译器模式专用。",
      NULL,
      NULL,
      {
         { "disabled", "禁用" },
         { "enabled", "启用" },
         { NULL, NULL },
      },
      NULL,
   },
   { NULL, NULL, NULL, NULL, NULL, NULL, {{0}}, NULL },
};

struct retro_core_options_v2 options_chs = {
   option_cats_chs,
   option_defs_chs
};

/* RETRO_LANGUAGE_TURKISH */

struct retro_core_option_v2_category option_cats_tr[] = {
   { NULL, NULL, NULL },
};

struct retro_core_option_v2_definition option_defs_tr[] = {
   {
      "pcsx_rearmed_frameskip",
      "Kare Atlama",
      NULL,
      "Görsel pürüzsüzlük pahasına performansı artırmak için ne kadar karenin atlanması gerektiğini seçin.",
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },
   {
      "pcsx_rearmed_bios",
      "BIOS Kullan",
      NULL,
      "Gerçek bios dosyasını (varsa) veya öykünmüş bios'u (HLE) kullanmanızı sağlar. Daha iyi uyumluluk için resmi bios dosyasını kullanmanız önerilir.",
      NULL,
      NULL,
      {
         { "auto", "otomatik" },
         { NULL, NULL },
      },
      "auto",
   },
   {
      "pcsx_rearmed_region",
      "Bölge",
      NULL,
      "Sistemin hangi bölgeden olduğunu seçin. NTSC için 60 Hz, PAL için 50 Hz.",
      NULL,
      NULL,
      {
         { "auto", "otomatik" },
         { NULL, NULL },
      },
      "auto",
   },
   {
      "pcsx_rearmed_memcard2",
      "İkinci Bellek Kartını Etkinleştir (Paylaşılan)",
      NULL,
      "2. Hafıza kartı yuvasını etkinleştirin. Bu hafıza kartı tüm oyunlar arasında paylaşılır.",
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },
   {
      "pcsx_rearmed_multitap1",
      "Multitap 1",
      NULL,
      "Bağlantı noktası 1'deki multitap'ı etkinleştirir / devre dışı bırakır ve izin veren oyunlarda 5 oyuncuya kadar izin verir.",
      NULL,
      NULL,
      {
         { "auto", "otomatik" },
         { NULL, NULL },
      },
      "auto",
   },
   {
      "pcsx_rearmed_multitap2",
      "Multitap 2",
      NULL,
      "Bağlantı noktası 2'deki multitap'ı etkinleştirir/devre dışı bırakır ve izin veren oyunlarda 8 oyuncuya kadar izin verir. Bunun çalışması için Multitap 1'in etkinleştirilmesi gerekir.",
      NULL,
      NULL,
      {
         { "auto", "otomatik" },
         { NULL, NULL },
      },
      "auto",
   },
   {
      "pcsx_rearmed_negcon_deadzone",
      "NegCon Twist Deadzone (Yüzdelik)",
      NULL,
      "Öykünülmüş neGcon kontrolörünün 'büküm' eylemini simüle ederken RetroPad sol analog çubuğunun ölü bölgesini ayarlar. Sürüklenme/istenmeyen girişi ortadan kaldırmak için kullanılır.",
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },
   {
      "pcsx_rearmed_negcon_response",
      "NegCon Twist Response",
      NULL,
      "Öykünülmüş neGcon kontrolörünün 'bükümünü' simule etmek için bir RetroPad sol analog çubuğu kullanırken analog cevabını belirtir.",
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },
   {
      "pcsx_rearmed_vibration",
      "Titreşimi Etkinleştir",
      NULL,
      "Titreşim özelliklerini destekleyen kontrolörler için titreşim geri bildirimini etkinleştirir.",
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },
   {
      "pcsx_rearmed_dithering",
      "Dithering Etkinleştir",
      NULL,
      "Kapalı ise, PSX'in renk bantlarıyla mücadele etmek için uyguladığı renk taklidi düzenini devre dışı bırakır.",
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },

#ifdef NEW_DYNAREC
   {
      "pcsx_rearmed_drc",
      "Dinamik Yeniden Derleyici",
      NULL,
      "Çekirdeğin dinamik yeniden derleyici veya tercüman(daha yavaş) CPU talimatlarını kullanmasını sağlar.",
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },
   {
      "pcsx_rearmed_psxclock",
      "PSX CPU Saat Hızı",
      NULL,
      "Overclock or under-clock the PSX CPU. Try adjusting this if the game is too slow, too fast or hangs."
#if defined(HAVE_PRE_ARMV7) && !defined(_3DS)
      " Default is 50."
#else
      " Default is 57."
#endif
      ,
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },
#endif /* NEW_DYNAREC */

#ifdef GPU_NEON
   {
      "pcsx_rearmed_neon_interlace_enable_v2",
      "Interlacing Mode'u etkinleştir",
      NULL,
      "Sahte tarama çizgileri efektini etkinleştirir.",
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },
   {
      "pcsx_rearmed_neon_enhancement_enable",
      "Geliştirilmiş Çözünürlük",
      NULL,
      "Düşük performans pahasına çift çözünürlükte işler.",
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },
   {
      "pcsx_rearmed_neon_enhancement_no_main",
      "Geliştirilmiş Çözünürlük (Speed Hack)",
      NULL,
      "Geliştirilmiş çözünürlük seçeneği için hız aşırtma(bazı oyunlarda sorun çıkartabilir).",
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },
#endif /* GPU_NEON */

   {
      "pcsx_rearmed_display_internal_fps",
      "Dahili FPS'yi görüntüle",
      NULL,
      "Etkinleştirildiğinde ekranda saniye başına kareyi gösterir.",
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },

   /* GPU PEOPS OPTIONS */
#ifdef GPU_PEOPS
   {
      "pcsx_rearmed_show_gpu_peops_settings",
      "Gelişmiş GPU Ayarlarını Göster",
      NULL,
      "Çeşitli GPU düzeltmelerini etkinleştirin veya devre dışı bırakın. Ayarların etkili olması için core'un yeniden başlatılması gerekebilir. NOT: Bu ayarın etkili olabilmesi için Hızlı Menü’nün değiştirilmesi gerekir.",
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },
   {
      "pcsx_rearmed_gpu_peops_odd_even_bit",
      "(GPU) Odd/Even Bit Hack",
      NULL,
      "Chrono Cross için gerekli.",
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },
   {
      "pcsx_rearmed_gpu_peops_expand_screen_width",
      "(GPU) Ekran Genişliğini Genişlet",
      NULL,
      "Capcom dövüş oyunları",
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },
   {
      "pcsx_rearmed_gpu_peops_ignore_brightness",
      "(GPU) Parlaklık Rengini Yoksay",
      NULL,
      "Lunar Silver Star Story oyunlarında siyah ekran",
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },
   {
      "pcsx_rearmed_gpu_peops_disable_coord_check",
      "(GPU) Koordinat Kontrolünü Devre Dışı Bırak",
      NULL,
      "Uyumluluk modu",
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },
   {
      "pcsx_rearmed_gpu_peops_lazy_screen_update",
      "(GPU) Tembel Ekran Güncellemesi",
      NULL,
      "Pandemonium 2",
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },
   {
      "pcsx_rearmed_gpu_peops_old_frame_skip",
      "(GPU) Eski Çerçeve Atlama",
      NULL,
      "Her ikinci kareyi atla",
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },
   {
      "pcsx_rearmed_gpu_peops_repeated_triangles",
      "(GPU) Tekrarlanan Düz Doku Üçgenleri",
      NULL,
      "Star Wars: Dark Forces için gerekli",
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },
   {
      "pcsx_rearmed_gpu_peops_quads_with_triangles",
      "(GPU) Üçgenler ile Dörtlü Çiz",
      NULL,
      "Daha iyi g renkler, daha kötü dokular",
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },
   {
      "pcsx_rearmed_gpu_peops_fake_busy_state",
      "(GPU) Sahte 'Gpu Meşgul' Konumları",
      NULL,
      "Çizimden sonra meşgul bayraklarını değiştir",
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },
#endif /* GPU_PEOPS */

   {
      "pcsx_rearmed_show_bios_bootlogo",
      "Bios Bootlogo'yu Göster",
      NULL,
      "Etkinleştirildiğinde, başlatırken veya sıfırlarken PlayStation logosunu gösterir. (Bazı oyunları bozabilir).",
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },
   {
      "pcsx_rearmed_spu_reverb",
      "Ses Yankısı",
      NULL,
      "Ses yankı efektini etkinleştirir veya devre dışı bırakır.",
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },
   {
      "pcsx_rearmed_spu_interpolation",
      "Ses Enterpolasyonu",
      NULL,
      NULL,
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },
   {
      "pcsx_rearmed_icache_emulation",
      "ICache Düzeltmleri",
      NULL,
      NULL,
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },

   /* ADVANCED OPTIONS */
   {
      "pcsx_rearmed_noxadecoding",
      "XA Kod Çözme",
      NULL,
      NULL,
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },
   {
      "pcsx_rearmed_nocdaudio",
      "CD Ses",
      NULL,
      NULL,
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },

#ifdef NEW_DYNAREC
   {
      "pcsx_rearmed_nosmccheck",
      "(Speed Hack) SMC Kontrollerini Devre Dışı Bırak",
      NULL,
      "Yükleme sırasında çökmelere neden olabilir, hafıza kartını bozabilir.",
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },
   {
      "pcsx_rearmed_gteregsunneeded",
      "(Speed Hack) GTE'nin Gereksiz Olduğunu Varsayın",
      NULL,
      "Grafiksel bozukluklara neden olabilir.",
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },
   {
      "pcsx_rearmed_nogteflags",
      "(Speed Hack) GTE Bayraklarını Devredışı Bırakın",
      NULL,
      "Grafiksel bozukluklara neden olur.",
      NULL,
      NULL,
      {
         { NULL, NULL },
      },
      NULL
   },
#endif /* NEW_DYNAREC */

   { NULL, NULL, NULL, NULL, NULL, NULL, {{0}}, NULL },
};

struct retro_core_options_v2 options_tr = {
   option_cats_tr,
   option_defs_tr
};

#ifdef __cplusplus
}
#endif

#endif