#!/usr/bin/env python3
"""
Generate an embedded cheat database C source file from .CHT cheat files.

Usage:
  python3 tools/gen_cheat_db.py <cheat_dir> <output_c_file>

The .CHT files use format:
  [Cheat Name]
  XXXXXXXX YYYY
  XXXXXXXX YYYY

The output is a C file with:
  - A sorted index array mapping game_id -> offset into data blob
  - A raw data blob with cheat entries
"""
import os
import re
import sys

def strip_to_cdrom_id(filename):
    """Convert a CHT filename to a CdromId match key.
    e.g. SCES_000.01 -> SCES00001 (strip non-alnum chars, remove .CHT extension)"""
    name = filename
    if name.endswith('.CHT'):
        name = name[:-4]
    elif name.endswith('.cht'):
        name = name[:-4]
    return ''.join(c for c in name if c.isalnum()).upper()


def parse_cht_file(filepath):
    """Parse a .CHT file and return list of (name, [(addr, value), ...]) tuples."""
    try:
        with open(filepath, 'rb') as f:
            data = f.read()
    except Exception as e:
        print(f"Warning: could not read {filepath}: {e}", file=sys.stderr)
        return []

    cheats = []
    current_name = None
    current_codes = []

    # Pattern for code line: 8 hex digits, space, 4 hex digits
    code_re = re.compile(rb'^([0-9A-Fa-f]{8})\s+([0-9A-Fa-f]{4})')

    for line in data.split(b'\n'):
        line = line.rstrip(b'\r')

        # Check for [name] header
        if line.startswith(b'[') and line.endswith(b']'):
            # Save previous cheat
            if current_name is not None and current_codes:
                cheats.append((current_name, current_codes))
            # Start new cheat
            name_bytes = line[1:-1]
            # Clean up name: remove trailing whitespace
            name_bytes = name_bytes.rstrip()
            if name_bytes:
                current_name = name_bytes
                current_codes = []
            else:
                current_name = None
            continue

        # Check for code line
        m = code_re.match(line)
        if m and current_name is not None:
            try:
                addr = int(m.group(1), 16)
                value = int(m.group(2), 16)
                current_codes.append((addr, value & 0xFFFF))
            except ValueError:
                pass

    # Save last cheat
    if current_name is not None and current_codes:
        cheats.append((current_name, current_codes))

    return cheats


def build_blob(game_data):
    """Build a binary blob from game data.
    Returns (blob_bytes, index_entries).
    index_entries is list of (game_id, offset_in_blob).
    """
    # Sort games by game_id for binary search
    sorted_games = sorted(game_data.keys())

    blob_parts = []
    index_entries = []

    for game_id in sorted_games:
        offset = len(b''.join(blob_parts))
        index_entries.append((game_id, offset))

        parts = []
        for name, codes in game_data[game_id]:
            # name_length (uint16 LE) + name bytes
            name_bytes = name
            assert len(name_bytes) < 65536, f"Cheat name too long: {name}"
            parts.append(len(name_bytes).to_bytes(2, 'little'))
            parts.append(name_bytes)
            # code_count (uint16 LE)
            assert len(codes) < 65536, f"Too many codes for cheat {name}: {len(codes)}"
            parts.append(len(codes).to_bytes(2, 'little'))
            # codes: addr (uint32 LE) + value (uint16 LE)
            for addr, value in codes:
                parts.append(addr.to_bytes(4, 'little'))
                parts.append(value.to_bytes(2, 'little'))
        # End of game marker: name_length uint16 = 0
        parts.append(b'\x00\x00')
        blob_parts.append(b''.join(parts))

    blob = b''.join(blob_parts)
    return blob, index_entries


def write_c_source(output_path, blob, index_entries):
    """Write the generated C source file."""

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("""/* Auto-generated cheat database - do not edit by hand */
/* Generated by tools/gen_cheat_db.py */
/* This file is included from libretro_cheats.c */

""")

        # Write the blob as a hex byte array
        f.write("static const uint8_t cheat_db_blob[] = {\n")
        for i in range(0, len(blob), 16):
            chunk = blob[i:i+16]
            hex_str = ', '.join(f'0x{b:02X}' for b in chunk)
            f.write(f"  {hex_str},\n")
        f.write("};\n\n")

        # Write the index array
        f.write(f"#define CHEAT_DB_GAME_COUNT {len(index_entries)}\n\n")

        f.write("""typedef struct {
  char game_id[12];
  uint32_t blob_offset;
} cheat_db_index_t;

""")

        f.write("static const cheat_db_index_t cheat_db_index[] = {\n")
        for game_id, offset in index_entries:
            # Pad game_id to 12 bytes with nulls
            padded = game_id[:11].ljust(12, '\0')
            hex_parts = ', '.join(f"'{c}'" if c != '\0' else "'\\0'" for c in padded)
            f.write(f"  {{ {{ {hex_parts} }}, {offset} }},\n")
        f.write("};\n\n")

        # Write helper to find game
        f.write("""static const cheat_db_index_t *cheat_db_find(const char *game_id)
{
  if (!game_id) return NULL;

  int lo = 0, hi = CHEAT_DB_GAME_COUNT - 1;
  while (lo <= hi) {
    int mid = (lo + hi) / 2;
    int cmp = strcmp(game_id, cheat_db_index[mid].game_id);
    if (cmp == 0)
      return &cheat_db_index[mid];
    else if (cmp < 0)
      hi = mid - 1;
    else
      lo = mid + 1;
  }
  return NULL;
}
""")

    print(f"Generated {output_path}: {len(index_entries)} games, {len(blob)} bytes blob")


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <cheat_dir> <output_c_file>")
        sys.exit(1)

    cheat_dir = sys.argv[1]
    output_path = sys.argv[2]

    # Parse all .CHT files
    game_data = {}
    file_count = 0
    cheat_count = 0
    code_count = 0

    for filename in sorted(os.listdir(cheat_dir)):
        if not filename.upper().endswith('.CHT'):
            continue
        filepath = os.path.join(cheat_dir, filename)
        game_id = strip_to_cdrom_id(filename)
        cheats = parse_cht_file(filepath)

        if not cheats:
            continue

        file_count += 1

        if game_id not in game_data:
            game_data[game_id] = []

        game_data[game_id].extend(cheats)
        cheat_count += len(cheats)
        for _, codes in cheats:
            code_count += len(codes)

    print(f"Parsed {file_count} files, {cheat_count} cheats, {code_count} codes, {len(game_data)} unique games")

    # Build blob and index
    blob, index_entries = build_blob(game_data)

    # Write C source
    write_c_source(output_path, blob, index_entries)


if __name__ == '__main__':
    main()
